name: Gated

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  func:
    name: Azure Function App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore -v minimal

      - name: Build Release
        run: >
          dotnet build
          -c Release
          -v minimal
          --no-restore
          --nologo

      - name: Test
        run: >
          dotnet test
          --collect "XPlat Code coverage"
          -r artifacts/tests
          -c Release
          -v minimal
          --no-build
          --nologo

      - name: Generate report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.0.2
        with:
          reports: artifacts/tests/**/coverage.cobertura.xml
          targetdir: artifacts/tests/Html
          reporttypes: Html

      - name: Publish test reports
        uses: actions/upload-artifact@v2
        with:
          name: tests
          path: artifacts/tests

  # infra:
  #   name: Azure Resource Manager
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Test
  #       id: testinfra
  #       uses: venura9/arm-ttk@master
  #       with:
  #         path: infra
  #         file: azuredeploy.json

  #     - name: Results for Run ARM-TTK with 'path'
  #       if: always()
  #       run: |
  #         content=${{ steps.testinfra.outputs.results }}
  #         echo 'Results $content'
