name: Gated

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  func:
    name: Azure Function App
    runs-on: ubuntu-latest
    env:
      TESTS_OUTPUT: artifacts/tests

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: .Net Restore
        run: dotnet restore

      - name: Build Release
        run: >
          dotnet build
          -c Release
          --no-restore
          --nologo

      - name: .Net Test
        run: >
          dotnet test
          --collect "XPlat Code coverage"
          -r ${{ env.TESTS_OUTPUT }}/coverage
          -c Release
          --no-restore
          --no-build
          --nologo

      - name: Generate report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.0.2
        with:
          reports: ${{ env.TESTS_OUTPUT }}/**/coverage.cobertura.xml
          targetdir: ${{ env.TESTS_OUTPUT }}/report
          reporttypes: Html

      - name: Publish tests artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tests
          path: ${{ env.TESTS_OUTPUT }}

  infra:
    name: Azure Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Bicep Build
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: infra/main.bicep
          outputFilePath: infra/azuredeploy1.json

      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1

      # - name: Git Pull
      #   run: git switch -c $GIT_BRANCH_NAME

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.GIT_BRANCH_NAME }}
          force: true
